version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./raw_db.txt:/app/raw_db.txt
    restart: on-failure

  mongodb:
    image: mongo:5.0 # Specify the version here
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - app-network
    restart: on-failure

  vue-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:80  # Assuming Vue.js app is running on port 80 inside the container
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
